language: php

dist: xenial

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - PHPUNIT_TEST=1
    - PHPCS_TEST=1

before_script:
  - export PATH=~/.composer/vendor/bin:$PATH
  - composer validate
  - composer require --no-update silverstripe/recipe-core:5.x-dev
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile
  - if [[ $PHPCS_TEST ]]; then composer global require squizlabs/php_codesniffer:^3 --prefer-dist --no-interaction --no-progress --no-suggest -o; fi
  - phpenv rehash

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests/php; fi
  - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi
